theme: jekyll-theme-minimal
logo: https://github.com/getmytech/getmytech.github.io/blob/master/getmytech.io.logo.PNG?raw=true
title: getmytech.io
description: cloud technology partner
show_downloads: false
